#can be run by typing 'make' in the terminal
#to remove all databases to start again, type 'make drop'

all: #runs database builder
	python db_builder.py
drop: discobandit.db #removes all tables in curr dir, be careful
	rm *.db